# Generated by rust2rpm 28
%bcond check 1

%global crate dotslash

Name:           rust-dotslash
Version:        0.5.9
Release:        %autorelease
Summary:        helper for simplified executable deployment

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/dotslash
Source:         %{crates_source}

# Automatically generated patch to strip dependencies and normalize metadata
Patch:          dotslash-fix-metadata-auto.diff

Patch:          metadata.diff

# Extracted from https://github.com/facebook/dotslash/pull/146.
# The PR upstream modifies the original Cargo.toml, but here we
# have the reformatted one, so only keep the code adjustments.
Patch:          0001-config.rs-update-to-jsonc-parser-0.32.patch
Patch:          0001-Cargo.toml-bump-blake3-dependency-to-1.8.5.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Command-line tool to facilitate fetching an executable, caching it, and
then running it.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE
%license LICENSE-MIT
%license LICENSE.dependencies
%doc README.md
%{_bindir}/dotslash

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
# Many tests fail in mock with: curl: (6) Could not resolve host: github.com
%cargo_test -- -- --skip={create_url_entry_tar_zst,fetch_simple,http__arg0,http__tar_xz__valid_executable,http__zst__valid_executable,create_url_entry_tar_gz,http__plain__valid_executable,clean_command_ok,http__xz__valid_executable,http__tar_zst__valid_executable,http__zip__valid_executable,http__gz__valid_executable,http__tar_gz__valid_executable,http__nonexistent_url}
%endif

%changelog
%autochangelog
